[tool.poetry]
name = "arduino-cli"
version = "0.0.0"
description = "Project used to run integration tests for the Arduino CLI"
authors = []

[tool.poetry.dependencies]
python = "^3.8"
pytest = "6.0.2"
simplejson = "3.17.0"
semver = "2.13.0"
pyserial = "3.4"
pyyaml = "5.3"
prometheus-client = "0.7.1"
requests = "2.22.0"
pytest-timeout = "1.3.4"
invoke = "1.4.1"
flake8 = "^3.8.3"
black = { version = "^19.10b0", allow-prereleases = true }
filelock = "^3.0.12"
pytest-xdist = "^2.1.0"
pytest_httpserver = "^0.3.5"
GitPython = "^3.1.12"

[tool.black]
line-length = 120
target-version = ["py38"]
